import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopBar from "./pages/shared/components/top-bar";
import Footer from "./pages/shared/components/footer";
import MobileSidePanel from "./pages/shared/components/mobile-side-panel";
import React from "react";
import { SidebarProvider } from "./context/SidebarContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Web Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          background: "#ecf0f1",
          minHeight: "100vh",
        }}
      >
        <SidebarProvider>
          <TopBar />
          <MobileSidePanel />
          {children}
          <Footer />
        </SidebarProvider>
      </body>
    </html>
  );
}
